name: currency_exchange
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  bottom_sheet: ^2.0.0
  dio: ^4.0.4
  dio_cache_interceptor: ^3.2.6
  dio_cache_interceptor_hive_store: ^3.1.1
  elementary: ^1.1.0
  elementary_test: ^1.1.0
  
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2
  mocktail: ^0.2.0
  path_provider: ^2.0.9
  provider: ^6.0.2
  shimmer: ^2.0.0
  surf_lint_rules: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
      - assets/json/currencies.json
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"